spring:
  datasource:
    url: jdbc:mysql://localhost:3307/liquidbase_db
    username: root
    password: root

liquidbase:
  change-log: classpath:/db/changelog/app-changelog.xml
  default-schema: liquidbase_db
